version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped

  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
